### ISSUE TITLE
Print Invoice Feature

### ISSUE THREAD

**Issue by mhamzajutt96** [Spl-Global/new_project#19]
[Clarifications _ Revisions for Order 2 Fiverr.txt](https://github.com/Spl-Global/new_project/files/3944080/Clarifications._.Revisions.for.Order.2.Fiverr.txt)
@imranhayat 
1. **I have displayed all the invoices on the Index page of the Application. So, on print Invoices call you have to print all the invoices of those tasks that are displaying on home page.**
2. **Only those tasks are displaying on home page that are completed.**
3. **Tasks displaying on Check Off page are `due_date = Today` tasks.** 
_Here we are print that tasks and by clicking on print button we are completed all those tasks and generating their invoices. On clicking of this button, you have to show another button, that is already displaying their saying print invoices._

**Comment by imranhayat** [comment]
Fixed and Checked
